# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\src\view\SomethingNew.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtCore import pyqtSlot
from PyQt5.QtWidgets import QWidget, QShortcut, QApplication, QMessageBox
from PyQt5.QtGui import QKeySequence


class Ui_MainWindow(QWidget):


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 727)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(360, 90, 331, 231))
        self.gridLayoutWidget.setMinimumSize(QtCore.QSize(5, 5))
        self.gridLayoutWidget.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.guess22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess22.setMinimumSize(QtCore.QSize(5, 5))
        self.guess22.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess22.setText("")
        self.guess22.setAlignment(QtCore.Qt.AlignCenter)
        self.guess22.setObjectName("guess22")
        self.gridLayout.addWidget(self.guess22, 1, 1, 1, 1)
        self.guess13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess13.setMinimumSize(QtCore.QSize(5, 5))
        self.guess13.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess13.setText("")
        self.guess13.setAlignment(QtCore.Qt.AlignCenter)
        self.guess13.setObjectName("guess13")
        self.gridLayout.addWidget(self.guess13, 0, 2, 1, 1)
        self.guess12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess12.setMinimumSize(QtCore.QSize(5, 5))
        self.guess12.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess12.setText("")
        self.guess12.setAlignment(QtCore.Qt.AlignCenter)
        self.guess12.setObjectName("guess12")
        self.gridLayout.addWidget(self.guess12, 0, 1, 1, 1)
        self.guess14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess14.setMinimumSize(QtCore.QSize(5, 5))
        self.guess14.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess14.setText("")
        self.guess14.setAlignment(QtCore.Qt.AlignCenter)
        self.guess14.setObjectName("guess14")
        self.gridLayout.addWidget(self.guess14, 0, 3, 1, 1)
        self.guess15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess15.setMinimumSize(QtCore.QSize(5, 5))
        self.guess15.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess15.setText("")
        self.guess15.setAlignment(QtCore.Qt.AlignCenter)
        self.guess15.setObjectName("guess15")
        self.gridLayout.addWidget(self.guess15, 0, 4, 1, 1)
        self.guess25 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess25.setMinimumSize(QtCore.QSize(5, 5))
        self.guess25.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess25.setText("")
        self.guess25.setAlignment(QtCore.Qt.AlignCenter)
        self.guess25.setObjectName("guess25")
        self.gridLayout.addWidget(self.guess25, 1, 4, 1, 1)
        self.guess31 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess31.setMinimumSize(QtCore.QSize(5, 5))
        self.guess31.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess31.setText("")
        self.guess31.setAlignment(QtCore.Qt.AlignCenter)
        self.guess31.setObjectName("guess31")
        self.gridLayout.addWidget(self.guess31, 2, 0, 1, 1)
        self.guess24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess24.setMinimumSize(QtCore.QSize(5, 5))
        self.guess24.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess24.setText("")
        self.guess24.setAlignment(QtCore.Qt.AlignCenter)
        self.guess24.setObjectName("guess24")
        self.gridLayout.addWidget(self.guess24, 1, 3, 1, 1)
        self.guess21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess21.setMinimumSize(QtCore.QSize(5, 5))
        self.guess21.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess21.setText("")
        self.guess21.setAlignment(QtCore.Qt.AlignCenter)
        self.guess21.setObjectName("guess21")
        self.gridLayout.addWidget(self.guess21, 1, 0, 1, 1)
        self.guess23 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess23.setMinimumSize(QtCore.QSize(5, 5))
        self.guess23.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess23.setText("")
        self.guess23.setAlignment(QtCore.Qt.AlignCenter)
        self.guess23.setObjectName("guess23")
        self.gridLayout.addWidget(self.guess23, 1, 2, 1, 1)
        self.guess11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess11.setMinimumSize(QtCore.QSize(5, 5))
        self.guess11.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess11.setLineWidth(3)
        self.guess11.setText("")
        self.guess11.setAlignment(QtCore.Qt.AlignCenter)
        self.guess11.setObjectName("guess11")
        self.gridLayout.addWidget(self.guess11, 0, 0, 1, 1)
        self.guess53 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess53.setMinimumSize(QtCore.QSize(5, 5))
        self.guess53.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess53.setText("")
        self.guess53.setAlignment(QtCore.Qt.AlignCenter)
        self.guess53.setObjectName("guess53")
        self.gridLayout.addWidget(self.guess53, 4, 2, 1, 1)
        self.guess55 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess55.setMinimumSize(QtCore.QSize(5, 5))
        self.guess55.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess55.setText("")
        self.guess55.setAlignment(QtCore.Qt.AlignCenter)
        self.guess55.setObjectName("guess55")
        self.gridLayout.addWidget(self.guess55, 4, 4, 1, 1)
        self.guess65 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess65.setMinimumSize(QtCore.QSize(5, 5))
        self.guess65.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess65.setText("")
        self.guess65.setAlignment(QtCore.Qt.AlignCenter)
        self.guess65.setObjectName("guess65")
        self.gridLayout.addWidget(self.guess65, 5, 4, 1, 1)
        self.guess63 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess63.setMinimumSize(QtCore.QSize(5, 5))
        self.guess63.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess63.setText("")
        self.guess63.setAlignment(QtCore.Qt.AlignCenter)
        self.guess63.setObjectName("guess63")
        self.gridLayout.addWidget(self.guess63, 5, 2, 1, 1)
        self.guess64 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess64.setMinimumSize(QtCore.QSize(5, 5))
        self.guess64.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess64.setText("")
        self.guess64.setAlignment(QtCore.Qt.AlignCenter)
        self.guess64.setObjectName("guess64")
        self.gridLayout.addWidget(self.guess64, 5, 3, 1, 1)
        self.guess44 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess44.setMinimumSize(QtCore.QSize(5, 5))
        self.guess44.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess44.setText("")
        self.guess44.setAlignment(QtCore.Qt.AlignCenter)
        self.guess44.setObjectName("guess44")
        self.gridLayout.addWidget(self.guess44, 3, 3, 1, 1)
        self.guess45 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess45.setMinimumSize(QtCore.QSize(5, 5))
        self.guess45.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess45.setText("")
        self.guess45.setAlignment(QtCore.Qt.AlignCenter)
        self.guess45.setObjectName("guess45")
        self.gridLayout.addWidget(self.guess45, 3, 4, 1, 1)
        self.guess41 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess41.setMinimumSize(QtCore.QSize(5, 5))
        self.guess41.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess41.setText("")
        self.guess41.setAlignment(QtCore.Qt.AlignCenter)
        self.guess41.setObjectName("guess41")
        self.gridLayout.addWidget(self.guess41, 3, 0, 1, 1)
        self.guess61 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess61.setMinimumSize(QtCore.QSize(5, 5))
        self.guess61.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess61.setText("")
        self.guess61.setAlignment(QtCore.Qt.AlignCenter)
        self.guess61.setObjectName("guess61")
        self.gridLayout.addWidget(self.guess61, 5, 0, 1, 1)
        self.guess51 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess51.setMinimumSize(QtCore.QSize(5, 5))
        self.guess51.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess51.setText("")
        self.guess51.setAlignment(QtCore.Qt.AlignCenter)
        self.guess51.setObjectName("guess51")
        self.gridLayout.addWidget(self.guess51, 4, 0, 1, 1)
        self.guess62 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess62.setMinimumSize(QtCore.QSize(5, 5))
        self.guess62.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess62.setText("")
        self.guess62.setAlignment(QtCore.Qt.AlignCenter)
        self.guess62.setObjectName("guess62")
        self.gridLayout.addWidget(self.guess62, 5, 1, 1, 1)
        self.guess52 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess52.setMinimumSize(QtCore.QSize(5, 5))
        self.guess52.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess52.setText("")
        self.guess52.setAlignment(QtCore.Qt.AlignCenter)
        self.guess52.setObjectName("guess52")
        self.gridLayout.addWidget(self.guess52, 4, 1, 1, 1)
        self.guess32 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess32.setMinimumSize(QtCore.QSize(5, 5))
        self.guess32.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess32.setText("")
        self.guess32.setAlignment(QtCore.Qt.AlignCenter)
        self.guess32.setObjectName("guess32")
        self.gridLayout.addWidget(self.guess32, 2, 1, 1, 1)
        self.guess33 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess33.setMinimumSize(QtCore.QSize(5, 5))
        self.guess33.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess33.setText("")
        self.guess33.setAlignment(QtCore.Qt.AlignCenter)
        self.guess33.setObjectName("guess33")
        self.gridLayout.addWidget(self.guess33, 2, 2, 1, 1)
        self.guess35 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess35.setMinimumSize(QtCore.QSize(5, 5))
        self.guess35.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess35.setText("")
        self.guess35.setAlignment(QtCore.Qt.AlignCenter)
        self.guess35.setObjectName("guess35")
        self.gridLayout.addWidget(self.guess35, 2, 4, 1, 1)
        self.guess34 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess34.setMinimumSize(QtCore.QSize(5, 5))
        self.guess34.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess34.setText("")
        self.guess34.setAlignment(QtCore.Qt.AlignCenter)
        self.guess34.setObjectName("guess34")
        self.gridLayout.addWidget(self.guess34, 2, 3, 1, 1)
        self.guess54 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess54.setMinimumSize(QtCore.QSize(5, 5))
        self.guess54.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess54.setText("")
        self.guess54.setAlignment(QtCore.Qt.AlignCenter)
        self.guess54.setObjectName("guess54")
        self.gridLayout.addWidget(self.guess54, 4, 3, 1, 1)
        self.guess43 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess43.setMinimumSize(QtCore.QSize(5, 5))
        self.guess43.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess43.setText("")
        self.guess43.setAlignment(QtCore.Qt.AlignCenter)
        self.guess43.setObjectName("guess43")
        self.gridLayout.addWidget(self.guess43, 3, 2, 1, 1)
        self.guess42 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.guess42.setMinimumSize(QtCore.QSize(5, 5))
        self.guess42.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-style: ridge;\n"
"border-width: 2px;\n"
"\n"
"")
        self.guess42.setText("")
        self.guess42.setAlignment(QtCore.Qt.AlignCenter)
        self.guess42.setObjectName("guess42")
        self.gridLayout.addWidget(self.guess42, 3, 1, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(160, 380, 806, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_10.setShortcut("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_2.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_11.setShortcut("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_2.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_12.setShortcut("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_2.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_13.setShortcut("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_2.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_14.setShortcut("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_2.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_15.setShortcut("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_2.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_16.setShortcut("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_2.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_17.setShortcut("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_2.addWidget(self.pushButton_17)
        self.pushButton_18 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_18.setShortcut("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_2.addWidget(self.pushButton_18)
        self.pushButton_19 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_19.setShortcut("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_2.addWidget(self.pushButton_19)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(160, 460, 791, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.aButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.aButton.setShortcut("")
        self.aButton.setObjectName("aButton")
        self.horizontalLayout_3.addWidget(self.aButton)
        self.sButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.sButton.setShortcut("")
        self.sButton.setObjectName("sButton")
        self.horizontalLayout_3.addWidget(self.sButton)
        self.dButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.dButton.setShortcut("")
        self.dButton.setObjectName("dButton")
        self.horizontalLayout_3.addWidget(self.dButton)
        self.fButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.fButton.setShortcut("")
        self.fButton.setObjectName("fButton")
        self.horizontalLayout_3.addWidget(self.fButton)
        self.gButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.gButton.setShortcut("")
        self.gButton.setObjectName("gButton")
        self.horizontalLayout_3.addWidget(self.gButton)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_6.setShortcut("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_7.setShortcut("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_8.setShortcut("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_9.setShortcut("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(160, 530, 791, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.backbutton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backbutton.sizePolicy().hasHeightForWidth())
        self.backbutton.setSizePolicy(sizePolicy)
        self.backbutton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("..\\src\\view\\back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backbutton.setIcon(icon)
        self.backbutton.setIconSize(QtCore.QSize(32, 32))
        self.backbutton.setShortcut("")
        self.backbutton.setObjectName("backbutton")
        self.horizontalLayout_5.addWidget(self.backbutton)
        self.pushButton_30 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_30.setShortcut("")
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_5.addWidget(self.pushButton_30)
        self.pushButton_31 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_31.setShortcut("")
        self.pushButton_31.setObjectName("pushButton_31")
        self.horizontalLayout_5.addWidget(self.pushButton_31)
        self.pushButton_32 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_32.setShortcut("")
        self.pushButton_32.setObjectName("pushButton_32")
        self.horizontalLayout_5.addWidget(self.pushButton_32)
        self.pushButton_33 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_33.setShortcut("")
        self.pushButton_33.setObjectName("pushButton_33")
        self.horizontalLayout_5.addWidget(self.pushButton_33)
        self.pushButton_34 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_34.setShortcut("")
        self.pushButton_34.setObjectName("pushButton_34")
        self.horizontalLayout_5.addWidget(self.pushButton_34)
        self.pushButton_35 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_35.setShortcut("")
        self.pushButton_35.setObjectName("pushButton_35")
        self.horizontalLayout_5.addWidget(self.pushButton_35)
        self.pushButton_36 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_36.setShortcut("")
        self.pushButton_36.setObjectName("pushButton_36")
        self.horizontalLayout_5.addWidget(self.pushButton_36)
        self.enterbutton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.enterbutton.setShortcut("")
        self.enterbutton.setObjectName("enterbutton")
        self.horizontalLayout_5.addWidget(self.enterbutton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_10.setText(_translate("MainWindow", "Q"))
        self.pushButton_11.setText(_translate("MainWindow", "W"))
        self.pushButton_12.setText(_translate("MainWindow", "E"))
        self.pushButton_13.setText(_translate("MainWindow", "R"))
        self.pushButton_14.setText(_translate("MainWindow", "T"))
        self.pushButton_15.setText(_translate("MainWindow", "Y"))
        self.pushButton_16.setText(_translate("MainWindow", "U"))
        self.pushButton_17.setText(_translate("MainWindow", "I"))
        self.pushButton_18.setText(_translate("MainWindow", "O"))
        self.pushButton_19.setText(_translate("MainWindow", "P"))
        self.aButton.setText(_translate("MainWindow", "A"))
        self.sButton.setText(_translate("MainWindow", "S"))
        self.dButton.setText(_translate("MainWindow", "D"))
        self.fButton.setText(_translate("MainWindow", "F"))
        self.gButton.setText(_translate("MainWindow", "G"))
        self.pushButton_6.setText(_translate("MainWindow", "H"))
        self.pushButton_7.setText(_translate("MainWindow", "J"))
        self.pushButton_8.setText(_translate("MainWindow", "K"))
        self.pushButton_9.setText(_translate("MainWindow", "L"))
        self.pushButton_30.setText(_translate("MainWindow", "Z"))
        self.pushButton_31.setText(_translate("MainWindow", "X"))
        self.pushButton_32.setText(_translate("MainWindow", "C"))
        self.pushButton_33.setText(_translate("MainWindow", "V"))
        self.pushButton_34.setText(_translate("MainWindow", "B"))
        self.pushButton_35.setText(_translate("MainWindow", "N"))
        self.pushButton_36.setText(_translate("MainWindow", "M"))
        self.enterbutton.setText(_translate("MainWindow", "Enter"))
        self.setButtonListeners()
        self.keyboardPressed()



    def setButtonListeners(self):
        self.BUTTONTEXT=self.aButton.text()

        self.aButton.clicked.connect(lambda ch, buttonThatWasPressed=self.aButton,buttontext=self.BUTTONTEXT:self.getButtonText(buttonThatWasPressed,buttontext))
        
        

    def getButtonText(self, buttonThatWasPressed,text):
        print("du har trykket på mig!",text)
        pass 
        
    def keyboardPressed(self):
        
        self.shortcut1 = QShortcut(QKeySequence('a'),self)
        self.shortcut1.activated.connect(self.on_open)
    
    @pyqtSlot()
    def on_open(self):
        print("A!!")





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    
    MainWindow.show()
    sys.exit(app.exec_())
